version: 2

project_name: prune

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: macos
    binary: prune
    main: ./cmd/prune
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_darwin_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_macos_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Thank you for using prune 🍀
