version: 2

project_name: prune

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux-windows
    binary: prune
    main: ./cmd/prune
    env:
      - CGO_ENABLED=1
      - ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache
      - ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache-local
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "386"
      - goos: linux
        goarch: "386"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-gnu
          - CXX=zig c++ -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-gnu
          - CXX=zig c++ -target aarch64-linux-gnu
      - goos: windows
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu
      - goos: windows
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-windows-gnu
          - CXX=zig c++ -target aarch64-windows-gnu

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux-windows_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Thank you for using prune 🍀
